CREATE PROCEDURE SP_Agregar_Admin
    @ID_ADMIN CHAR(4),
    @NOM VARCHAR(100),
    @APE VARCHAR(100),
    @CORREO VARCHAR(100),
    @PASS VARCHAR(8),
    @DOC_DNI INT,
    @F_NAC DATE,
    @TELF VARCHAR(9)
AS 
BEGIN
    INSERT INTO ADMINISTRADOR (ID_ADMINISTRADOR, NOMBRES, APELLIDOS, EMAIL, CONTRASEÑA, DNI, FECHA_NACIMIENTO, TELEFONO) 
    VALUES (@ID_ADMIN, @NOM, @APE, @CORREO, @PASS, @DOC_DNI, @F_NAC, @TELF);
END;
GO

EXEC SP_Agregar_Admin 
    'A002', 
    'Carlos', 
    'Mendoza', 
    'cmendoza@makea.pe', 
    'Admin123', 
    76543210, 
    '1990-05-14', 
    '987654321';
GO

CREATE PROCEDURE SP_Listar_Admin
AS 
BEGIN
    SELECT * FROM ADMINISTRADOR;
END;
GO



--Separación para Prodcuto:
CREATE TABLE PRODUCTO (
	ID_PRODUCTO CHAR (4) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL,
	CATEGORIA VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(255) NOT NULL,
	STOCK INT NOT NULL,
	PRECIO DECIMAL(10, 2) NOT NULL,
	Fecha_Creacion DATE NOT NULL,
	Fecha_Expiracion DATE NOT NULL
);
GO
CREATE PROCEDURE SP_Agregar_Producto
    @ID_PROD CHAR(4),
    @NOM VARCHAR(100),
    @CAT VARCHAR(50),
    @DESCR VARCHAR(255),
    @STK INT,
    @PREC DECIMAL(10,2),
    @F_CREA DATE,
    @F_EXP DATE
    
AS 
BEGIN
    INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, CATEGORIA, DESCRIPCION, STOCK, PRECIO, Fecha_Creacion, Fecha_Expiracion) 
    VALUES (@ID_PROD, @NOM, @CAT, @DESCR, @STK, @PREC, @F_CREA, @F_EXP);
END;
GO


EXEC SP_Agregar_Producto 
    'P004', 
    'Chocotejas de Pisco Sour', 
    'Chocoteja', 
    'Deliciosa chocoteja llena de manjar', 
    200, 
    2.50, 
    '2026-06-25',  
    '2026-07-25'; 
GO


CREATE PROCEDURE SP_Listar_Productos
AS 
BEGIN
    SELECT * FROM PRODUCTO;
END;
GO

--Separación para Cliente:
CREATE PROCEDURE SP_Agregar_Cliente
    @ID_CLI CHAR(4),
    @NOM VARCHAR(100),
    @APE VARCHAR(100),
    @CORREO VARCHAR(100),
    @PASS VARCHAR(8),
    @DOC_DNI INT,
    @F_NAC DATE,
    @TELF VARCHAR(9)
AS 
BEGIN
    INSERT INTO CLIENTE (ID_CLIENTE, NOMBRES, APELLIDOS, EMAIL, CONTRASEÑA, DNI, FECHA_NACIMIENTO, TELEFONO) 
    VALUES (@ID_CLI, @NOM, @APE, @CORREO, @PASS, @DOC_DNI, @F_NAC, @TELF);
END;
GO
CREATE PROCEDURE SP_Listar_Clientes
AS 
BEGIN
    SELECT * FROM CLIENTE;
END;
GO



EXEC SP_Listar_Clientes;
GO

EXEC SP_Listar_Admin;
GO

EXEC SP_Listar_Productos;
GO




