CREATE TABLE ADMINISTRADOR(
	ID_ADMINISTRADOR CHAR(4) NOT NULL PRIMARY KEY, 
	NOMBRES VARCHAR(100) NOT NULL,
	APELLIDOS VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	CONTRASEÑA VARCHAR(8) NOT NULL,  
	DNI INT NOT NULL UNIQUE,        
	FECHA_NACIMIENTO DATE NOT NULL,
	TELEFONO VARCHAR(9) NOT NULL UNIQUE 
);
GO

CREATE TABLE CLIENTE(
	ID_CLIENTE CHAR(4) NOT NULL PRIMARY KEY,
	NOMBRES VARCHAR(100) NOT NULL,
	APELLIDOS VARCHAR(100) NOT NULL, 
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	CONTRASEÑA VARCHAR(8) NOT NULL,  -- Cambiado a VARCHAR(8)
	DNI INT NOT NULL UNIQUE,         -- Cambiado a tipo INT
	FECHA_NACIMIENTO DATE NOT NULL,
	TELEFONO VARCHAR(9) NOT NULL UNIQUE 
);
GO

CREATE TABLE PRODUCTO (
	ID_PRODUCTO CHAR(4) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL,
	CATEGORIA VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(255) NOT NULL,
	STOCK INT NOT NULL,
	PRECIO DECIMAL(10, 2) NOT NULL,
	Fecha_Creacion DATE NOT NULL,
	Fecha_Expiracion DATE NOT NULL,
	ID_ADMINISTRADOR CHAR(4) NOT NULL FOREIGN KEY REFERENCES ADMINISTRADOR(ID_ADMINISTRADOR)
);
GO

SET DATEFORMAT dmy;
GO


INSERT INTO ADMINISTRADOR (ID_ADMINISTRADOR, NOMBRES, APELLIDOS, EMAIL, CONTRASEÑA, DNI, FECHA_NACIMIENTO, TELEFONO)
VALUES ('A001', 'Juan Carlos', 'Perez Gomez', 'juancitoperezoso@gmail.com', '12345678', 78451263, '15/07/1985','963547812');
GO


INSERT INTO CLIENTE (ID_CLIENTE, NOMBRES, APELLIDOS, EMAIL, CONTRASEÑA, DNI, FECHA_NACIMIENTO, TELEFONO)
VALUES ('C001', 'Maria Fernanda', 'Lopez Sanchez', 'marialopezsanchez09@gmail.com', '22222222', 91234567, '22/11/1990', '987654321');
GO


INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, CATEGORIA, DESCRIPCION, STOCK, PRECIO, Fecha_Creacion, Fecha_Expiracion, ID_ADMINISTRADOR)
VALUES 
('P001', 'Chocotejas de Maracuya', 'Chocoteja', 'Llenas de manjar blanco y sabor maracuya', 100, 2.50, '25/06/2026', '25/07/2026', 'A001'),
('P002', 'Cuchareables', 'Postre', 'En envases individuales', 200, 5.00, '25/06/2026', '25/07/2026', 'A001'),
('P003', 'Chocotejas de Oreo', 'Chocoteja', 'Llenas de manjar blanco y trozos de galleta oreo', 300, 2.50, '25/06/2026', '25/07/2026', 'A001');
GO


SELECT * FROM ADMINISTRADOR;
SELECT * FROM PRODUCTO;
SELECT * FROM CLIENTE;
GO

