CREATE DATABASE MAKEA;
GO
USE MAKEA;
GO

CREATE TABLE ADMINISTRADOR(
	ID_ADMINISTRADOR CHAR(4) NOT NULL, 
	NOMBRES VARCHAR(100) NOT NULL,
	APELLIDOS VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	CONTRASEÑA VARCHAR(8) NOT NULL,  
	DNI CHAR(8) NOT NULL,        
	FECHA_NACIMIENTO DATE NOT NULL,
	TELEFONO VARCHAR(9) NOT NULL, 

	CONSTRAINT PK_ID_ADMINISTRADOR PRIMARY KEY (ID_ADMINISTRADOR),
	CONSTRAINT UQ_EMAIL_ADMIN UNIQUE (EMAIL),
	CONSTRAINT UQ_DNI_ADMIN UNIQUE (DNI),
	CONSTRAINT UQ_TELEFONO_ADMIN UNIQUE (TELEFONO)
);
GO

CREATE SEQUENCE Seq_Cliente_ID
    START WITH 0
    INCREMENT BY 1;
GO

CREATE TABLE CLIENTE (
    ID_CLIENTE CHAR(4) DEFAULT ('C' + RIGHT('000' + CAST(NEXT VALUE FOR Seq_Cliente_ID AS VARCHAR(3)), 3)) NOT NULL,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL, 
    DNI CHAR(8) NOT NULL, 
    CONTRASEÑA CHAR(8) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONO CHAR(9) NOT NULL, 

	CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT UQ_DNI_CLIENTE UNIQUE (DNI),
	CONSTRAINT UQ_EMAIL_CLIENTE UNIQUE (EMAIL),
	CONSTRAINT UQ_TELEFONO_CLIENTE UNIQUE (TELEFONO),
    CONSTRAINT CHK_TELEFONO_CLIENTE CHECK (TELEFONO LIKE '9%'),    
    CONSTRAINT CHK_EMAIL_CLIENTE CHECK (
	EMAIL LIKE '%@gmail.com' OR 
	EMAIL LIKE '%@hotmail.com' OR 
	EMAIL LIKE '%@yahoo.com' OR
	EMAIL LIKE '%@outlook.com')   
);
GO

CREATE SEQUENCE Seq_Chocotejas
    START WITH 1
    INCREMENT BY 1;
GO

CREATE SEQUENCE Seq_Cuchareables
    START WITH 1
    INCREMENT BY 1;
GO

CREATE TABLE PRODUCTO (
	
	ID_PRODUCTO CHAR(5) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	CATEGORIA VARCHAR(15) NOT NULL,
	DESCRIPCION VARCHAR(255) NOT NULL,
	STOCK INT NOT NULL,
	PRECIO DECIMAL(10, 2) NOT NULL,
	Fecha_Creacion DATE DEFAULT GETDATE() NOT NULL,
	Fecha_Expiracion DATE NOT NULL, 
	ID_ADMINISTRADOR CHAR(4) NOT NULL,
	
	CONSTRAINT PK_ID_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
	CONSTRAINT FK_PRO_IDADMINISTRADOR FOREIGN KEY (ID_ADMINISTRADOR) REFERENCES ADMINISTRADOR(ID_ADMINISTRADOR),
	CONSTRAINT CHK_CATEGORIA CHECK (CATEGORIA IN ('Chocotejas', 'Cuchareables')), 
	CONSTRAINT CHK_PRO_PRECIO CHECK (PRECIO >= 0),
	CONSTRAINT CHK_PRO_STOCK CHECK (STOCK >= 0),
	CONSTRAINT CHK_FECHA_VENCIMIENTO CHECK (Fecha_Expiracion > Fecha_Creacion)
);
GO




CREATE SEQUENCE Seq_CARRITO_ID
    START WITH 0
    INCREMENT BY 1;
GO

CREATE TABLE CARRITO (
	ID_CARRITO CHAR(6) DEFAULT ('CAR' + RIGHT('000' + CAST(NEXT VALUE FOR Seq_CARRITO_ID AS VARCHAR(3)), 3)) NOT NULL,
	ID_CLIENTE CHAR(4) NOT NULL,
	MONTO_TOTAL DECIMAL(10, 2) NOT NULL,
	CANTIDAD_PRODUCTOS INT NOT NULL,

	CONSTRAINT PK_ID_CARRITO PRIMARY KEY (ID_CARRITO),
	CONSTRAINT FK_CAR_IDCLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	CONSTRAINT CHK_Cantidad_Productos CHECK (CANTIDAD_PRODUCTOS >= 0),
	CONSTRAINT UQ_CARRITO_CLIENTE UNIQUE (ID_CLIENTE)
);
Go	


CREATE SEQUENCE Seq_DETALLE_CARRITO_ID
    START WITH 0
    INCREMENT BY 1;
GO

CREATE TABLE DETALLE_CARRITO (
	ID_DETALLE_CARRITO CHAR(5) DEFAULT ('DC' + RIGHT('000' + CAST(NEXT VALUE FOR Seq_DETALLE_CARRITO_ID AS VARCHAR(3)), 3)) NOT NULL,
	ID_CARRITO CHAR(6) NOT NULL, 
	-- Ampliado a CHAR(5)
	ID_PRODUCTO CHAR(5) NOT NULL,
	CANTIDAD INT NOT NULL,
	PRECIO DECIMAL(10, 2) NOT NULL,

	CONSTRAINT PK_ID_DETALLE_CARRITO PRIMARY KEY (ID_DETALLE_CARRITO),
	CONSTRAINT FK_DC_ID_CARRITO FOREIGN KEY (ID_CARRITO) REFERENCES CARRITO(ID_CARRITO),
	CONSTRAINT FK_DC_ID_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
	CONSTRAINT CHK_DC_PRECIO CHECK (PRECIO >= 0),
	CONSTRAINT CHK_DC_CANTIDAD CHECK (CANTIDAD >= 0)
);
GO

-- VENTA:
CREATE SEQUENCE Seq_VENTA_ID
    START WITH 0
    INCREMENT BY 1;
GO

CREATE TABLE VENTA (
    ID_VENTA CHAR(4) DEFAULT ('V' + RIGHT('000' + CAST(NEXT VALUE FOR Seq_VENTA_ID AS VARCHAR(3)), 3)) NOT NULL,
    ID_CLIENTE CHAR(4) NOT NULL,
    FECHA_HORA DATETIME DEFAULT GETDATE() NOT NULL, 
    IGV DECIMAL(10,2) NOT NULL, 

    CONSTRAINT PK_ID_VENTA PRIMARY KEY (ID_VENTA),
    CONSTRAINT FK_VE_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);
GO

-- Detalle Venta:
CREATE SEQUENCE Seq_DETALLE_VENTA_ID
    START WITH 0
    INCREMENT BY 1;
GO

CREATE TABLE DETALLE_VENTA (
    ID_DETALLE_VENTA CHAR(5) DEFAULT ('DV' + RIGHT('000' + CAST(NEXT VALUE FOR Seq_DETALLE_VENTA_ID AS VARCHAR(3)), 3)) NOT NULL,
    ID_VENTA CHAR(4) NOT NULL, 
	-- Ampliado a CHAR(5)
    ID_PRODUCTO CHAR(5) NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    PRECIO DECIMAL(10, 2) NOT NULL, 

    CONSTRAINT PK_ID_DETALLE_VENTA PRIMARY KEY (ID_DETALLE_VENTA),
    CONSTRAINT FK_DV_ID_VENTA FOREIGN KEY (ID_VENTA) REFERENCES VENTA(ID_VENTA),
    CONSTRAINT FK_DV_ID_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
    CONSTRAINT CHK_DV_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT CHK_DV_PRECIO_UNITARIO CHECK (PRECIO_UNITARIO >= 0),
    CONSTRAINT CHK_DV_PRECIO CHECK (PRECIO >= 0)
);
GO

SET DATEFORMAT dmy;
GO


